# Generated by Django 4.1.5 on 2023-01-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('startingBid', models.IntegerField()),
                ('imageURL', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
