# Generated by Django 4.1.5 on 2023-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('currentBid', models.IntegerField()),
                ('numberOfBids', models.IntegerField()),
                ('owner', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
