# Generated by Django 4.1.5 on 2023-01-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_comments_listing_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='Bids',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='currentBid',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='numberOfBids',
            new_name='number',
        ),
    ]
