# Generated by Django 4.1.5 on 2023-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bid_bids_rename_currentbid_bids_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bids',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.CharField(max_length=64),
        ),
    ]
