# Generated by Django 4.1.5 on 2023-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bids_current_alter_bids_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watching', to='auctions.listing'),
        ),
    ]
