# Generated by Django 4.1.5 on 2023-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'electronics'), ('2', 'books'), ('3', 'clothes'), ('4', 'instruments'), ('5', 'other')], max_length=64),
        ),
    ]
